window.newsItems = [
  {
    id: 1,
    title: "Emergency memo leaked: AI procurement now requires incident rehearsal proof",
    deck: "Three agencies moved from paper-compliance to simulation-tested compliance after high-profile audit failures.",
    category: "Policy",
    timestamp: "06:13 UTC",
    edition: "Global Desk",
    readTime: "3 min",
    author: "Rina K",
    coverage: "Regulation",
    confidence: 92,
    impact: "High",
    labels: ["threat", "hotspot", "psychic"],
    tone: "urgent"
  },
  {
    id: 2,
    title: "Alien-blue dashboard goes public: ocean anomaly monitor spots triple heat filament",
    deck: "Researchers flagged a non-seasonal cluster with synchronized movement across shipping corridors.",
    category: "Science",
    timestamp: "05:58 UTC",
    edition: "Science Desk",
    readTime: "4 min",
    author: "Mika L",
    coverage: "Climate Systems",
    confidence: 84,
    impact: "Medium",
    labels: ["alien", "acid"],
    tone: "info"
  },
  {
    id: 3,
    title: "Cover story: chip foundries report cleaner queue maps, enterprise demand steadies",
    deck: "Quarterly guidance indicates better packaging throughput and fewer allocation shocks.",
    category: "Business",
    timestamp: "05:41 UTC",
    edition: "Markets",
    readTime: "5 min",
    author: "Dana V",
    coverage: "Semiconductors",
    confidence: 88,
    impact: "Medium",
    labels: ["psychic", "premium"],
    tone: "premium"
  },
  {
    id: 4,
    title: "Zero-day relay burst: mobile stack patched, exploitation attempts already detected",
    deck: "Security teams advise accelerated rollout windows and stricter dependency visibility in MDM fleets.",
    category: "Tech",
    timestamp: "05:33 UTC",
    edition: "Infra Desk",
    readTime: "3 min",
    author: "Kei N",
    coverage: "Mobile Security",
    confidence: 95,
    impact: "Critical",
    labels: ["threat", "alien"],
    tone: "urgent"
  },
  {
    id: 5,
    title: "Culture lane expands: documentary studios launch weekly signal capsule formats",
    deck: "Short editorial arcs with confidence notes outperform long-form drops in completion rates.",
    category: "Culture",
    timestamp: "05:12 UTC",
    edition: "Culture",
    readTime: "4 min",
    author: "Yuri S",
    coverage: "Documentary",
    confidence: 81,
    impact: "Low",
    labels: ["psychic", "premium"],
    tone: "premium"
  },
  {
    id: 6,
    title: "City trial gets weird: autonomous buses reroute around late-night crowd pulses",
    deck: "Transit labs found anomaly-aware routing reduced delays while improving passenger safety metrics.",
    category: "City",
    timestamp: "04:59 UTC",
    edition: "Metro",
    readTime: "3 min",
    author: "Ari M",
    coverage: "Urban Mobility",
    confidence: 79,
    impact: "Medium",
    labels: ["acid", "hotspot"],
    tone: "weird"
  },
  {
    id: 7,
    title: "Open-source policy tracker adds live confidence badges for each regulation draft",
    deck: "Editors can compare wording volatility and lobbying pressure snapshots in one pane.",
    category: "Policy",
    timestamp: "04:42 UTC",
    edition: "Policy Lab",
    readTime: "4 min",
    author: "Nora T",
    coverage: "Gov Tech",
    confidence: 86,
    impact: "Medium",
    labels: ["alien", "psychic"],
    tone: "info"
  },
  {
    id: 8,
    title: "Premium brief: constrained-context models cut hallucination bursts in support queues",
    deck: "Support teams trade creative breadth for reliability under strict SLA windows.",
    category: "Tech",
    timestamp: "04:19 UTC",
    edition: "AI Ops",
    readTime: "6 min",
    author: "Liza P",
    coverage: "Applied AI",
    confidence: 90,
    impact: "High",
    labels: ["premium", "psychic"],
    tone: "premium"
  }
];

window.tickerItems = [
  "Threat lane +18% mentions in last 2h",
  "Policy drafts now include rollback protocol fields",
  "Anomaly desk opened dedicated moderation queue",
  "Premium flashes capped to 8% of visual density"
];